// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeWS63-fK0TP-QmulWH1WrpkoKKUw8-QQ',
    appId: '1:359314838510:web:7baa5cf55c349e1aeb74ff',
    messagingSenderId: '359314838510',
    projectId: 'sofrasofra-a3344',
    authDomain: 'sofrasofra-a3344.firebaseapp.com',
    storageBucket: 'sofrasofra-a3344.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiXLPBSNu6--IbJ78vr82aIdJkRshW79s',
    appId: '1:359314838510:android:8287daa6423a49c5eb74ff',
    messagingSenderId: '359314838510',
    projectId: 'sofrasofra-a3344',
    storageBucket: 'sofrasofra-a3344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2cRetGdzsc10WSZB7vwgAEgYG7jqasfs',
    appId: '1:359314838510:ios:b7897ceeff3e224ceb74ff',
    messagingSenderId: '359314838510',
    projectId: 'sofrasofra-a3344',
    storageBucket: 'sofrasofra-a3344.firebasestorage.app',
    iosBundleId: 'com.example.sofrasofraArenaV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2cRetGdzsc10WSZB7vwgAEgYG7jqasfs',
    appId: '1:359314838510:ios:b7897ceeff3e224ceb74ff',
    messagingSenderId: '359314838510',
    projectId: 'sofrasofra-a3344',
    storageBucket: 'sofrasofra-a3344.firebasestorage.app',
    iosBundleId: 'com.example.sofrasofraArenaV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeWS63-fK0TP-QmulWH1WrpkoKKUw8-QQ',
    appId: '1:359314838510:web:fae97c00abd11f09eb74ff',
    messagingSenderId: '359314838510',
    projectId: 'sofrasofra-a3344',
    authDomain: 'sofrasofra-a3344.firebaseapp.com',
    storageBucket: 'sofrasofra-a3344.firebasestorage.app',
  );
}
